/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.ci.cd.b;
import test.ci.cd.*;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("test desde A: "+new test.ci.cd.App().getGreeting());
    }
}
